### ISSUE TITLE
what is this repo for ?

### ISSUE THREAD

**Issue by fabcotech** [guillaumearm/PathToTarkov#1]
Hi, I'm curious to know what this repo is for, I think the README would need more context :)

All the ebst

**Comment by guillaumearm** [comment]
Hi, you right :-)

It's a mod for [Single Player tarkov](https://www.sp-tarkov.com/), an offline version of the famous game [Escape from Tarkov](https://www.escapefromtarkov.com/)

Cheers ;-)
